language: cpp
script:
  - echo | sudo apt-add-repository ppa:ondrej/php
  - sudo apt-get update
  - sudo echo Y | apt-get install php7.0
  - sudo wget -O phpunit https://phar.phpunit.de/phpunit-4.phar
  - sudo chmod +x phpunit
  - ./phpunit --version
  - ./phpunit --coverage-clover=coverage.xml
  - g++ web/gsqasm.cpp -o web/gsqasm
sudo: true
addons:
  apt:
    packages:
        - build-essential
