language: cpp
script:
  - apt-add-repository ppa:ondrej/php
  - apt-get update
  - echo Y | apt-get install php7.0
  - wget -O phpunit https://phar.phpunit.de/phpunit-6.phar
  - chmod +x phpunit
  - ./phpunit --version
  - ./phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - g++ web/gsqasm.cpp -o web/gsqasm
sudo: true
addons:
  apt:
    packages:
        - build-essential
