language: cpp
script:
  - wget -O phpunit https://phar.phpunit.de/phpunit-6.phar
  - chmod +x phpunit
  - ./phpunit --version
  - ./phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - g++ web/gsqasm.cpp -o web/gsqasm
sudo: true
addons:
  apt:
    packages:
        - build-essential
        - php7.0
